# Generated by Django 3.2.9 on 2021-12-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemones',
            name='name',
            field=models.CharField(default='vacio', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equip',
            field=models.CharField(default=0, max_length=1500),
        ),
    ]
