# Generated by Django 3.2.9 on 2021-11-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
