# Generated by Django 3.2.9 on 2021-12-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_auto_20211201_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemones',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
