# Generated by Django 3.2.9 on 2021-12-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='deita',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
