# Generated by Django 3.2.9 on 2021-12-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_alter_pokemones_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemones',
            name='name',
            field=models.CharField(max_length=1500, verbose_name='Nombre'),
        ),
    ]
