# Generated by Django 3.2.9 on 2021-12-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0004_auto_20211130_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deita',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
