# Generated by Django 3.2.9 on 2021-12-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0005_auto_20211201_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pokemones',
        ),
        migrations.DeleteModel(
            name='Pokemones',
        ),
    ]
