# Generated by Django 3.2.9 on 2021-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0005_auto_20211130_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equip',
            field=models.CharField(default=0, max_length=300, verbose_name='Equipo'),
        ),
    ]
