# Generated by Django 3.2.9 on 2021-12-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0006_auto_20211201_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pokemon1',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pokemon2',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pokemon3',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pokemon4',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pokemon5',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pokemon6',
            field=models.CharField(default=0, max_length=1500),
        ),
    ]
