# Generated by Django 3.2.9 on 2021-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0006_profile_equip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equip',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
