# Generated by Django 3.2.9 on 2021-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_pokemon1',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_pokemon2',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_pokemon3',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_pokemon4',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_pokemon5',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_pokemon6',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
