# Generated by Django 3.2.9 on 2021-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0010_auto_20211202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
    ]
