# Generated by Django 3.2.9 on 2021-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon1',
            field=models.CharField(default='defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon2',
            field=models.CharField(default='defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon3',
            field=models.CharField(default='defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon4',
            field=models.CharField(default='defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon5',
            field=models.CharField(default='defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon6',
            field=models.CharField(default='defectimg.png', max_length=1500),
        ),
    ]
