# Generated by Django 3.2.9 on 2021-12-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0012_auto_20211202_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon1',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon2',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon3',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon4',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon5',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pokemon6',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
    ]
