# Generated by Django 3.2.9 on 2021-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pokemon1',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon2',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon3',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon4',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon5',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon6',
            field=models.CharField(default='/media/defectimg.png', max_length=1500),
        ),
    ]
