# Generated by Django 3.2.9 on 2021-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0015_auto_20211202_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vacio', max_length=1500)),
                ('imag', models.ImageField(default='defectimg.png', upload_to='')),
                ('equipo', models.CharField(default=0, max_length=1500)),
                ('dificultad', models.CharField(default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Enemigo',
            },
        ),
    ]
