# Generated by Django 3.2.9 on 2021-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0016_enemigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemigo',
            name='dificultad',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='name',
            field=models.CharField(default='Vacio', max_length=50),
        ),
    ]
