# Generated by Django 3.2.9 on 2021-12-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0017_auto_20211202_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enemigo',
            options={},
        ),
    ]
