# Generated by Django 3.2.9 on 2021-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0020_alter_enemigo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon1',
            field=models.CharField(default='/media/defectimg.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon2',
            field=models.CharField(default='/media/defectimg.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon3',
            field=models.CharField(default='/media/defectimg.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon4',
            field=models.CharField(default='/media/defectimg.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon5',
            field=models.CharField(default='/media/defectimg.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon6',
            field=models.CharField(default='/media/defectimg.png', max_length=50),
        ),
    ]
