# Generated by Django 3.2.9 on 2021-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0021_auto_20211205_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='victorias',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
