# Generated by Django 3.2.9 on 2021-12-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0022_profile_victorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='victorias',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
