# Generated by Django 3.2.9 on 2021-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0024_alter_profile_victorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equip',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
