# Generated by Django 3.2.9 on 2021-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0026_auto_20211208_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agua',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hiperPocion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maxPocion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pocion',
            field=models.IntegerField(default=0),
        ),
    ]
