# Generated by Django 3.2.9 on 2021-12-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0027_auto_20211208_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
