# Generated by Django 3.2.9 on 2021-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0030_poketeam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poketeam',
            options={'ordering': ['pokeFk']},
        ),
        migrations.AddField(
            model_name='poketeam',
            name='slot2',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='poketeam',
            name='slot3',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='poketeam',
            name='slot4',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='poketeam',
            name='slot5',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='poketeam',
            name='slot6',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='poketeam',
            name='slot1',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
    ]
