# Generated by Django 3.2.9 on 2021-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0031_auto_20211213_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slot1',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot2',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot3',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot4',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot5',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot6',
            field=models.ImageField(default='defectimg.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='PokeTeam',
        ),
    ]
