# Generated by Django 3.2.9 on 2021-12-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0033_alter_profile_slot1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slot1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slot2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slot3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slot4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slot5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slot6',
        ),
    ]
